markdown: kramdown
highlighter: rouge
permalink: /posts/:title
rdiscount:
  extensions: [smart]

collections:
  tricks:
    output: false

# https://github.com/jekyll/jekyll/issues/302
permalink: pretty
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename/
